### ISSUE TITLE
Cambiar tecnologías trabajos

### ISSUE THREAD

**Issue by carcamcue** [enredacoop/wenreda#6]
Los trabajos que son con **CONSUL**
- Ruby on Rails
- PostgreSQL
- Ubuntu
- HTML
- CSS
- JavaScript
- Consul (esta tecnología dijo Pablo que también la deberíamos resaltar junto al screenshot).

**ICAS**
- Plone
- Python
- HTML
- CSS
- JavaScript
- AJAX

**Festival de Cine**
- Drupal8
- API Rest
- HTML
- CSS
- JavaScript

_De los demás proyectos no tengo las tecnologías, habría que preguntar a Pablo._

**Comment by fatimamartinez** [comment]
@pablovg2 Hay que cambiar las tecnologías de algún otro proyecto??

**Comment by pablovg2** [comment]
No, creo que los que hay ya están bien.

**Comment by carcamcue** [comment]
Cambiadas con nuevos iconos.
